export * from './mainPage';
export * from './logIn.Page';
export * from './createArticlePage';
export * from './myArticlesPage';
export * from './articlePage';
export * from './homePage';
export * from './settingsPage';
export * from './favoritesPage';
export * from './profilePage';
